// <auto-generated />
using System;
using ContratacaoService.Infra.Data.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ContratacaoService.Infra.Data.Migrations
{
    [DbContext(typeof(ContratacaoDbContext))]
    [Migration("20260211225737_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ContratacaoService.Domain.Entities.Contratacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataContratacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_contratacao");

                    b.Property<Guid>("PropostaId")
                        .HasColumnType("uuid")
                        .HasColumnName("proposta_id");

                    b.HasKey("Id");

                    b.HasIndex("PropostaId")
                        .IsUnique()
                        .HasDatabaseName("ix_contratacoes_proposta_id");

                    b.ToTable("contratacoes", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
